# Generated by Django 4.1.3 on 2023-10-20 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('img_preview_1', models.ImageField(upload_to='course/preview/1/%Y/%m/%d/', verbose_name='1 Фотография 260*300')),
                ('img_preview_2', models.ImageField(upload_to='course/preview/2/%Y/%m/%d/', verbose_name='2 Фотография 260*300')),
                ('img_preview_3', models.ImageField(upload_to='course/preview/3/%Y/%m/%d/', verbose_name='3 Фотография 260*300')),
                ('img_main', models.ImageField(upload_to='course/img/%Y/%m/%d/', verbose_name='Главная фотография')),
                ('start_point', models.IntegerField(verbose_name='Start point')),
                ('end_point', models.IntegerField(verbose_name='End point')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursesAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор курсов',
                'verbose_name_plural': 'Авторы курсов',
            },
        ),
        migrations.CreateModel(
            name='CoursesCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория курсов',
                'verbose_name_plural': 'Категории курсов',
            },
        ),
        migrations.CreateModel(
            name='CoursesChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование главы')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('point', models.IntegerField(verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Глава курсов',
                'verbose_name_plural': 'Главы курсов',
            },
        ),
        migrations.CreateModel(
            name='CoursesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_price', models.BooleanField(default=False, verbose_name='Бесплатный/платный')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена курсов',
                'verbose_name_plural': 'Цены курсов',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc', models.TextField(blank=True, null=True, verbose_name='Описание о себе')),
                ('count_point', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('courses', models.ManyToManyField(blank=True, null=True, to='server.course', verbose_name='Курсы')),
                ('projects', models.ManyToManyField(blank=True, null=True, to='server.project', verbose_name='Проекты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='Chapter',
            field=models.ManyToManyField(to='server.courseschapter', verbose_name='Главы'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.coursesauthor', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='course',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.coursescat', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.coursesprice', verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_many',
            field=models.ManyToManyField(to='server.student', verbose_name='Студенты'),
        ),
    ]
