# Generated by Django 4.1.3 on 2023-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescat',
            name='cat_id',
            field=models.CharField(default='tab', max_length=155, verbose_name='id категории'),
            preserve_default=False,
        ),
    ]
